
load('predictionCoefficients.mat')

MeanErrorTable = table(...
    [   round(mean(modelFun(BlueBeta, BlueX) - BlueY),3); ...
        round(mean(modelFun(BlueBeta, GreenX) - GreenY),3); ...
        round(mean(modelFun(BlueBeta, PurpleX) - PurpleY),3); ...
        round(mean(modelFun(BlueBeta, RedX) - RedY),3)], ...
    [   round(mean(modelFun(GreenBeta, BlueX) - BlueY),3); ...
        round(mean(modelFun(GreenBeta, GreenX) - GreenY),3); ...
        round(mean(modelFun(GreenBeta, PurpleX) - PurpleY),3); ...
        round(mean(modelFun(GreenBeta, RedX) - RedY),3)], ...
    [   round(mean(modelFun(PurpleBeta, BlueX) - BlueY),3); ...
        round(mean(modelFun(PurpleBeta, GreenX) - GreenY),3); ...
        round(mean(modelFun(PurpleBeta, PurpleX) - PurpleY),3); ...
        round(mean(modelFun(PurpleBeta, RedX) - RedY),3)], ...
    [   round(mean(modelFun(RedBeta, BlueX) - BlueY),3); ...
        round(mean(modelFun(RedBeta, GreenX) - GreenY),3); ...
        round(mean(modelFun(RedBeta, PurpleX) - PurpleY),3); ...
        round(mean(modelFun(RedBeta, RedX) - RedY),3)], ...
    'VariableNames', {'Group_1_Videos', 'Group_2_Videos', 'Group_3_Videos', 'Group_4_Videos'}, ...
    'RowNames', {'Group 1 Coefficients', 'Group 2 Coefficients', 'Group 3 Coefficients', 'Group 4 Coefficients'})

StandardDeviationErrorTable = table(...
    [   round(std(modelFun(BlueBeta, BlueX) - BlueY),3); ...
        round(std(modelFun(BlueBeta, GreenX) - GreenY),3); ...
        round(std(modelFun(BlueBeta, PurpleX) - PurpleY),3); ...
        round(std(modelFun(BlueBeta, RedX) - RedY),3)], ...
    [   round(std(modelFun(GreenBeta, BlueX) - BlueY),3); ...
        round(std(modelFun(GreenBeta, GreenX) - GreenY),3); ...
        round(std(modelFun(GreenBeta, PurpleX) - PurpleY),3); ...
        round(std(modelFun(GreenBeta, RedX) - RedY),3)], ...
    [   round(std(modelFun(PurpleBeta, BlueX) - BlueY),3); ...
        round(std(modelFun(PurpleBeta, GreenX) - GreenY),3); ...
        round(std(modelFun(PurpleBeta, PurpleX) - PurpleY),3); ...
        round(std(modelFun(PurpleBeta, RedX) - RedY),3)], ...
    [   round(std(modelFun(RedBeta, BlueX) - BlueY),3); ...
        round(std(modelFun(RedBeta, GreenX) - GreenY),3); ...
        round(std(modelFun(RedBeta, PurpleX) - PurpleY),3); ...
        round(std(modelFun(RedBeta, RedX) - RedY),3)], ...
    'VariableNames', {'Group_1_Videos', 'Group_2_Videos', 'Group_3_Videos', 'Group_4_Videos'}, ...
    'RowNames', {'Group 1 Coefficients', 'Group 2 Coefficients', 'Group 3 Coefficients', 'Group 4 Coefficients'})
