load('VideoParameters.mat')

group1 = [11 20 8 9 18 10 7];
group2 = [1 23 17];
group3 = [2 4 5 6 14];
group4 = [12 19 22];

Group1RawVideoParameters = table(...
    round(SAD(group1), 3, 'significant')', ...
    round(edginess(group1), 3, 'significant')', ...
    round(brightness(group1), 3, 'significant')', ...
    round(blurriness(group1), 3, 'significant')', ...
    'VariableNames', {'SAD', 'Edginess', 'Brightness', 'Blurriness'}, ...
    'RowNames', cellstr(names(group1)))

Group2RawVideoParameters = table(...
    round(SAD(group2), 3, 'significant')', ...
    round(edginess(group2), 3, 'significant')', ...
    round(brightness(group2), 3, 'significant')', ...
    round(blurriness(group2), 3, 'significant')', ...
    'VariableNames', {'SAD', 'Edginess', 'Brightness', 'Blurriness'}, ...
    'RowNames', cellstr(names(group2)))

Group3RawVideoParameters = table(...
    round(SAD(group3), 3, 'significant')', ...
    round(edginess(group3), 3, 'significant')', ...
    round(brightness(group3), 3, 'significant')', ...
    round(blurriness(group3), 3, 'significant')', ...
    'VariableNames', {'SAD', 'Edginess', 'Brightness', 'Blurriness'}, ...
    'RowNames', cellstr(names(group3)))

Group4RawVideoParameters = table(...
    round(SAD(group4), 3, 'significant')', ...
    round(edginess(group4), 3, 'significant')', ...
    round(brightness(group4), 3, 'significant')', ...
    round(blurriness(group4), 3, 'significant')', ...
    'VariableNames', {'SAD', 'Edginess', 'Brightness', 'Blurriness'}, ...
    'RowNames', cellstr(names(group4)))

SADz = zscore(SAD([group1 group2 group3 group4]));
edginessz = zscore(edginess([group1 group2 group3 group4]));
brightnessz = zscore(brightness([group1 group2 group3 group4]));
blurrinessz = zscore(blurriness([group1 group2 group3 group4]));

Group1VideoParameterZscores = table(...
    round(SADz(1:length(group1)), 3, 'significant')', ...
    round(edginessz(1:length(group1)), 3, 'significant')', ...
    round(brightnessz(1:length(group1)), 3, 'significant')', ...
    round(blurrinessz(1:length(group1)), 3, 'significant')', ...
    'VariableNames', {'SAD', 'Edginess', 'Brightness', 'Blurriness'}, ...
    'RowNames', cellstr(names(group1)))

Group2VideoParameterZscores = table(...
    round(SADz(1+length(group1):length([group1 group2])), 3, 'significant')', ...
    round(edginessz(1+length(group1):length([group1 group2])), 3, 'significant')', ...
    round(brightnessz(1+length(group1):length([group1 group2])), 3, 'significant')', ...
    round(blurrinessz(1+length(group1):length([group1 group2])), 3, 'significant')', ...
    'VariableNames', {'SAD', 'Edginess', 'Brightness', 'Blurriness'}, ...
    'RowNames', cellstr(names(group2)))

Group3VideoParameterZscores = table(...
    round(SADz(1+length([group1 group2]):length([group1 group2 group3])), 3, 'significant')', ...
    round(edginessz(1+length([group1 group2]):length([group1 group2 group3])), 3, 'significant')', ...
    round(brightnessz(1+length([group1 group2]):length([group1 group2 group3])), 3, 'significant')', ...
    round(blurrinessz(1+length([group1 group2]):length([group1 group2 group3])), 3, 'significant')', ...
    'VariableNames', {'SAD', 'Edginess', 'Brightness', 'Blurriness'}, ...
    'RowNames', cellstr(names(group3)))

Group4VideoParameterZscores = table(...
    round(SADz(1+length([group1 group2 group3]):length([group1 group2 group3 group4])), 3, 'significant')', ...
    round(edginessz(1+length([group1 group2 group3]):length([group1 group2 group3 group4])), 3, 'significant')', ...
    round(brightnessz(1+length([group1 group2 group3]):length([group1 group2 group3 group4])), 3, 'significant')', ...
    round(blurrinessz(1+length([group1 group2 group3]):length([group1 group2 group3 group4])), 3, 'significant')', ...
    'VariableNames', {'SAD', 'Edginess', 'Brightness', 'Blurriness'}, ...
    'RowNames', cellstr(names(group4)))
